// Code generated by protoc-gen-go.
// source: message/message.proto
// DO NOT EDIT!

/*
Package message is a generated protocol buffer package.

It is generated from these files:
	message/message.proto

It has these top-level messages:
	Message
*/
package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Message_KIND int32

const (
	Message_REQUEST Message_KIND = 0
	Message_ACCEPT  Message_KIND = 1
	Message_DATA    Message_KIND = 2
)

var Message_KIND_name = map[int32]string{
	0: "REQUEST",
	1: "ACCEPT",
	2: "DATA",
}
var Message_KIND_value = map[string]int32{
	"REQUEST": 0,
	"ACCEPT":  1,
	"DATA":    2,
}

func (x Message_KIND) Enum() *Message_KIND {
	p := new(Message_KIND)
	*p = x
	return p
}
func (x Message_KIND) String() string {
	return proto.EnumName(Message_KIND_name, int32(x))
}
func (x *Message_KIND) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Message_KIND_value, data, "Message_KIND")
	if err != nil {
		return err
	}
	*x = Message_KIND(value)
	return nil
}
func (Message_KIND) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Message struct {
	Kind             *Message_KIND `protobuf:"varint,1,req,name=Kind,enum=message.Message_KIND" json:"Kind,omitempty"`
	Data             []byte        `protobuf:"bytes,2,opt,name=Data" json:"Data,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message) GetKind() Message_KIND {
	if m != nil && m.Kind != nil {
		return *m.Kind
	}
	return Message_REQUEST
}

func (m *Message) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "message.Message")
	proto.RegisterEnum("message.Message_KIND", Message_KIND_name, Message_KIND_value)
}

var fileDescriptor0 = []byte{
	// 131 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x87, 0xd2, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xec, 0x50, 0xae,
	0x52, 0x3a, 0x17, 0xbb, 0x2f, 0x84, 0x29, 0xa4, 0xcc, 0xc5, 0xe2, 0x9d, 0x99, 0x97, 0x22, 0xc1,
	0xa8, 0xc0, 0xa4, 0xc1, 0x67, 0x24, 0xaa, 0x07, 0xd3, 0x01, 0x95, 0xd7, 0xf3, 0xf6, 0xf4, 0x73,
	0x11, 0xe2, 0xe1, 0x62, 0x71, 0x49, 0x2c, 0x49, 0x94, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x51, 0xd2,
	0x04, 0x6a, 0x01, 0x89, 0x72, 0x73, 0xb1, 0x07, 0xb9, 0x06, 0x86, 0xba, 0x06, 0x87, 0x08, 0x30,
	0x08, 0x71, 0x71, 0xb1, 0x39, 0x3a, 0x3b, 0xbb, 0x06, 0x84, 0x08, 0x30, 0x0a, 0x71, 0x00, 0x95,
	0x3b, 0x86, 0x38, 0x0a, 0x30, 0x01, 0x02, 0x00, 0x00, 0xff, 0xff, 0x8e, 0x79, 0xc2, 0x96, 0x89,
	0x00, 0x00, 0x00,
}
